/* Auto-generated by scripts/gen_fleet_manifests.py — do not edit. */
#include "fleet_manifest_catalog.h"
#include "stdbool.h"
#include <string.h>

const fleet_manifest_entry_t fleet_manifest_catalog[FLEET_MANIFEST_CATALOG_COUNT] = {
  {
    .host_type_id = 999,
    .host_type = "template_host",
    .description = "Template host for fleet Zigbee integration",
    .manifest_version = 1,
    .report_interval_ms = 1000,
    .max_airtime_bytes = 64,
    .reading_count = 2,
    .readings = {
      {
        .key = "value_a",
        .tlv_id = 16,
        .type = FLEET_MANIFEST_FLOAT,
        .unit = "",
        .required = true,
      },
      {
        .key = "value_b",
        .tlv_id = 17,
        .type = FLEET_MANIFEST_UINT8,
        .unit = "",
        .required = false,
      },
    },
  },
  {
    .host_type_id = 1,
    .host_type = "ul212_ble_fetch",
    .description = "Tenet UL212 fuel level over BLE",
    .manifest_version = 1,
    .report_interval_ms = 1000,
    .max_airtime_bytes = 64,
    .reading_count = 6,
    .readings = {
      {
        .key = "height_mm",
        .tlv_id = 16,
        .type = FLEET_MANIFEST_FLOAT,
        .unit = "mm",
        .required = true,
      },
      {
        .key = "smooth_mm",
        .tlv_id = 17,
        .type = FLEET_MANIFEST_FLOAT,
        .unit = "mm",
        .required = false,
      },
      {
        .key = "temperature_c",
        .tlv_id = 18,
        .type = FLEET_MANIFEST_FLOAT,
        .unit = "C",
        .required = false,
      },
      {
        .key = "signal",
        .tlv_id = 19,
        .type = FLEET_MANIFEST_UINT8,
        .unit = "",
        .required = false,
      },
      {
        .key = "valid_echo",
        .tlv_id = 20,
        .type = FLEET_MANIFEST_UINT8,
        .unit = "",
        .required = false,
      },
      {
        .key = "tilt_deg",
        .tlv_id = 21,
        .type = FLEET_MANIFEST_UINT8,
        .unit = "",
        .required = false,
      },
    },
  },
};

const fleet_manifest_entry_t *fleet_manifest_find(uint16_t host_type_id)
{
  for (size_t i = 0; i < FLEET_MANIFEST_CATALOG_COUNT; i++) {
    if (fleet_manifest_catalog[i].host_type_id == host_type_id) {
      return &fleet_manifest_catalog[i];
    }
  }
  return NULL;
}

const fleet_manifest_entry_t *fleet_manifest_find_by_name(const char *host_type)
{
  if (!host_type) return NULL;
  for (size_t i = 0; i < FLEET_MANIFEST_CATALOG_COUNT; i++) {
    if (strcmp(fleet_manifest_catalog[i].host_type, host_type) == 0) {
      return &fleet_manifest_catalog[i];
    }
  }
  return NULL;
}
