#pragma once

/* Minimal, framework-free HTML/JS control page served at GET /. Kept as a
 * plain C string (adjacent string-literal concatenation) so it can be baked
 * straight into the firmware image without a filesystem/SPIFFS partition. */
static const char TRANSPORT_HTTP_INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>ELM327 C6</title>\n"
"<style>\n"
"body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:16px;background:#111;color:#eee;}\n"
"h1{font-size:1.3em;margin:0 0 4px;} h2{font-size:1em;color:#8bd;margin:20px 0 8px;}\n"
".card{background:#1c1c1c;border:1px solid #333;border-radius:8px;padding:12px;margin-bottom:14px;}\n"
"button{background:#2b6cb0;color:#fff;border:none;border-radius:5px;padding:8px 12px;cursor:pointer;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"button:hover{background:#3182ce;} button.danger{background:#c53030;} button.danger:hover{background:#e53e3e;}\n"
"button.secondary{background:#2d3748;} button.secondary:hover{background:#4a5568;}\n"
"input,select{background:#000;color:#eee;border:1px solid #444;border-radius:5px;padding:8px;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"table{width:100%;border-collapse:collapse;font-size:0.9em;}\n"
"td,th{border-bottom:1px solid #333;padding:6px;text-align:left;}\n"
"tr.devrow{cursor:pointer;} tr.devrow:hover{background:#222;}\n"
".pill{display:inline-block;padding:3px 8px;border-radius:10px;font-size:0.8em;margin:2px 6px 2px 0;}\n"
".ok{background:#22543d;color:#9ae6b4;} .bad{background:#742a2a;color:#feb2b2;}\n"
"pre{background:#000;border:1px solid #333;border-radius:5px;padding:8px;white-space:pre-wrap;word-break:break-all;max-height:180px;overflow:auto;}\n"
"small,.hint{color:#999;font-size:0.85em;}\n"
".grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;}\n"
".metric{background:#000;border:1px solid #333;border-radius:6px;padding:10px;}\n"
".metric .v{font-size:1.4em;font-weight:600;} .metric .k{color:#8bd;font-size:0.8em;}\n"
"@media (max-width:480px){.grid{grid-template-columns:1fr 1fr;}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<h1>ELM327 C6</h1>\n"
"<small>SoftAP bridge for phone control. Keep mobile data off while on ELM327-C6.</small>\n"
"\n"
"<div class=\"card\" id=\"statusCard\">\n"
"<h2>Status</h2>\n"
"<div id=\"statusOut\">loading...</div>\n"
"<div style=\"margin-top:8px;\">\n"
"<button onclick=\"refreshStatus()\">Refresh</button>\n"
"<button class=\"secondary\" onclick=\"doInit()\">Run init + 0100</button>\n"
"</div>\n"
"<div id=\"initMsg\" class=\"hint\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Live values</h2>\n"
"<div class=\"grid\" id=\"liveGrid\">\n"
"<div class=\"metric\"><div class=\"k\">RPM</div><div class=\"v\" id=\"vRpm\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Speed</div><div class=\"v\" id=\"vSpeed\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Coolant</div><div class=\"v\" id=\"vCool\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Voltage</div><div class=\"v\" id=\"vVolt\">-</div></div>\n"
"</div>\n"
"<table id=\"teleTable\" style=\"margin-top:10px;\"><thead><tr><th>cmd</th><th>name</th><th>value</th><th>unit</th><th>age</th></tr></thead><tbody></tbody></table>\n"
"<small id=\"teleEvent\"></small>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>BLE adapter</h2>\n"
"<button onclick=\"doScan()\">Scan</button>\n"
"<button onclick=\"refreshDevices()\">Refresh list</button>\n"
"<button class=\"danger\" onclick=\"doDisconnect()\">Disconnect</button>\n"
"<div id=\"scanMsg\" class=\"hint\"></div>\n"
"<table id=\"devTable\"><thead><tr><th>#</th><th>Name</th><th>Addr</th><th>RSSI</th></tr></thead><tbody></tbody></table>\n"
"<p class=\"hint\">Tap a row to connect. Your adapter may show as unnamed (MODAXE OBDII often has no BLE name). Prefer the strongest nearby device after phone Bluetooth is off. Connected adapters stop advertising — Disconnect to rescan.</p>\n"
"<div id=\"selectMsg\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Profile / protocol</h2>\n"
"<select id=\"profileSel\"></select>\n"
"<button onclick=\"activateProfile()\">Activate + init</button>\n"
"<div id=\"profileMsg\" class=\"hint\">can_11_500 = ISO15765 CAN 11bit/500k (modern cars). fleet_basic = auto protocol.</div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Raw command</h2>\n"
"<input id=\"rawCmd\" type=\"text\" placeholder=\"e.g. 010C or ATRV\" style=\"width:180px;\">\n"
"<button onclick=\"sendCmd()\">Send</button>\n"
"<pre id=\"cmdOut\">(no command sent yet)</pre>\n"
"</div>\n"
"\n"
"<script>\n"
"async function getJSON(url, opts){\n"
"  try {\n"
"    const r = await fetch(url, Object.assign({cache:'no-store'}, opts||{}));\n"
"    let body = null;\n"
"    try { body = await r.json(); } catch(e) {}\n"
"    return {ok: r.ok, status: r.status, body: body};\n"
"  } catch(e) {\n"
"    return {ok: false, status: 0, body: null, error: String(e)};\n"
"  }\n"
"}\n"
"function pill(ok, t, f){ return '<span class=\"pill '+(ok?'ok':'bad')+'\">'+(ok?t:f)+'</span>'; }\n"
"\n"
"async function refreshStatus(){\n"
"  const res = await getJSON('/api/status');\n"
"  if (!res.body) {\n"
"    document.getElementById('statusOut').textContent =\n"
"      'Cannot reach ESP API. Join Wi-Fi ELM327-C6 / elm327c6, disable mobile data, open http://192.168.4.1/';\n"
"    return;\n"
"  }\n"
"  const s = res.body;\n"
"  document.getElementById('statusOut').innerHTML =\n"
"    pill(s.ble_connected, 'BLE connected', 'BLE disconnected') +\n"
"    pill(s.elm_ready, 'ELM ready', 'ELM not ready') +\n"
"    pill(s.poller_enabled, 'Polling on', 'Polling paused') +\n"
"    '<span class=\"pill\">peer: '+(s.peer_addr||'-')+'</span>' +\n"
"    '<span class=\"pill\">profile: '+(s.active_profile||'-')+'</span>' +\n"
"    '<span class=\"pill\">up: '+(s.uptime_s||0)+'s</span>';\n"
"}\n"
"\n"
"async function doInit(){\n"
"  document.getElementById('initMsg').textContent = 'Running AT init + 0100 (may take ~15s)...';\n"
"  const res = await getJSON('/api/elm/init', {method:'POST'});\n"
"  document.getElementById('initMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function doScan(){\n"
"  document.getElementById('scanMsg').textContent = 'scanning...';\n"
"  const res = await getJSON('/api/ble/scan', {method:'POST'});\n"
"  if (res.status === 409) {\n"
"    document.getElementById('scanMsg').textContent = (res.body && res.body.message) || 'already connected — disconnect first';\n"
"    return;\n"
"  }\n"
"  document.getElementById('scanMsg').textContent = res.ok ? 'scan started; refreshing in 6s...' : 'scan failed';\n"
"  if (res.ok) setTimeout(refreshDevices, 6500);\n"
"}\n"
"\n"
"async function refreshDevices(){\n"
"  const res = await getJSON('/api/ble/devices');\n"
"  const tbody = document.querySelector('#devTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  if (!res.body || !res.body.devices) return;\n"
"  document.getElementById('scanMsg').textContent = res.body.devices.length + ' device(s)';\n"
"  res.body.devices.forEach(function(d){\n"
"    const tr = document.createElement('tr');\n"
"    tr.className = 'devrow';\n"
"    tr.innerHTML = '<td>'+d.index+'</td><td>'+(d.name||'(unnamed)')+'</td><td>'+d.addr+'</td><td>'+d.rssi+'</td>';\n"
"    tr.onclick = function(){ connectIndex(d.index); };\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"}\n"
"\n"
"async function connectIndex(idx){\n"
"  document.getElementById('selectMsg').textContent = 'connecting index '+idx+'...';\n"
"  const res = await getJSON('/api/ble/select', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({index: idx})\n"
"  });\n"
"  document.getElementById('selectMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function doDisconnect(){\n"
"  const res = await getJSON('/api/ble/disconnect', {method:'POST'});\n"
"  document.getElementById('selectMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus();\n"
"}\n"
"\n"
"async function sendCmd(){\n"
"  const cmd = document.getElementById('rawCmd').value.trim();\n"
"  if (!cmd) return;\n"
"  document.getElementById('cmdOut').textContent = 'sending...';\n"
"  const res = await getJSON('/api/elm/cmd', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({cmd: cmd})\n"
"  });\n"
"  document.getElementById('cmdOut').textContent = res.body ? JSON.stringify(res.body, null, 2) : ('HTTP '+res.status);\n"
"}\n"
"\n"
"async function refreshProfiles(){\n"
"  const res = await getJSON('/api/profiles');\n"
"  const sel = document.getElementById('profileSel');\n"
"  if (!res.body || !res.body.profiles) return;\n"
"  const prev = sel.value;\n"
"  sel.innerHTML = '';\n"
"  res.body.profiles.forEach(function(name){\n"
"    const opt = document.createElement('option');\n"
"    opt.value = name; opt.textContent = name + (name === res.body.active ? ' (active)' : '');\n"
"    sel.appendChild(opt);\n"
"  });\n"
"  if (prev) sel.value = prev; else if (res.body.active) sel.value = res.body.active;\n"
"}\n"
"\n"
"async function activateProfile(){\n"
"  const name = document.getElementById('profileSel').value;\n"
"  if (!name) return;\n"
"  document.getElementById('profileMsg').textContent = 'activating '+name+' (init may take ~15s)...';\n"
"  const res = await getJSON('/api/profiles/active', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({name: name})\n"
"  });\n"
"  document.getElementById('profileMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshProfiles(); refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"function setLive(id, sample){\n"
"  const el = document.getElementById(id);\n"
"  if (!sample || !sample.ok) { el.textContent = '-'; return; }\n"
"  const v = (typeof sample.value === 'number') ? sample.value.toFixed(1) : sample.value;\n"
"  el.textContent = v + (sample.unit ? (' '+sample.unit) : '');\n"
"}\n"
"\n"
"async function refreshTelemetry(){\n"
"  const res = await getJSON('/api/telemetry');\n"
"  if (!res.body) return;\n"
"  const samples = res.body.samples || [];\n"
"  const byName = {};\n"
"  samples.forEach(function(s){ byName[s.name] = s; byName[s.cmd] = s; });\n"
"  setLive('vRpm', byName.rpm || byName['010C']);\n"
"  setLive('vSpeed', byName.speed || byName['010D']);\n"
"  setLive('vCool', byName.coolant_c || byName['0105']);\n"
"  setLive('vVolt', byName.voltage || byName.ATRV);\n"
"  const tbody = document.querySelector('#teleTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  samples.slice().reverse().forEach(function(s){\n"
"    const tr = document.createElement('tr');\n"
"    const ageS = s.age_ms != null ? (s.age_ms/1000).toFixed(1)+'s' : '-';\n"
"    tr.innerHTML = '<td>'+s.cmd+'</td><td>'+s.name+'</td>' +\n"
"      '<td>'+(s.ok ? (s.value.toFixed ? s.value.toFixed(2) : s.value) : 'n/a')+'</td>' +\n"
"      '<td>'+(s.unit||'')+'</td><td>'+ageS+'</td>';\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"  const ev = res.body.last_event;\n"
"  document.getElementById('teleEvent').textContent = ev ? ('last event: '+ev.kind) : '';\n"
"}\n"
"\n"
"function tick(){ refreshStatus(); refreshTelemetry(); }\n"
"refreshStatus(); refreshDevices(); refreshProfiles(); refreshTelemetry();\n"
"setInterval(tick, 2000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
