#pragma once

/* Minimal, framework-free HTML/JS control page served at GET /. Kept as a
 * plain C string (adjacent string-literal concatenation) so it can be baked
 * straight into the firmware image without a filesystem/SPIFFS partition. */
static const char TRANSPORT_HTTP_INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>ELM327 C6</title>\n"
"<style>\n"
"body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:16px;background:#111;color:#eee;}\n"
"h1{font-size:1.3em;margin:0 0 4px;} h2{font-size:1em;color:#8bd;margin:20px 0 8px;}\n"
".card{background:#1c1c1c;border:1px solid #333;border-radius:8px;padding:12px;margin-bottom:14px;}\n"
"button{background:#2b6cb0;color:#fff;border:none;border-radius:5px;padding:6px 12px;cursor:pointer;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"button:hover{background:#3182ce;} button.danger{background:#c53030;} button.danger:hover{background:#e53e3e;}\n"
"input,select{background:#000;color:#eee;border:1px solid #444;border-radius:5px;padding:5px 8px;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"table{width:100%;border-collapse:collapse;font-size:0.9em;}\n"
"td,th{border-bottom:1px solid #333;padding:4px 6px;text-align:left;}\n"
".pill{display:inline-block;padding:2px 8px;border-radius:10px;font-size:0.8em;margin-right:6px;}\n"
".ok{background:#22543d;color:#9ae6b4;} .bad{background:#742a2a;color:#feb2b2;}\n"
"pre{background:#000;border:1px solid #333;border-radius:5px;padding:8px;white-space:pre-wrap;word-break:break-all;max-height:160px;overflow:auto;}\n"
"small{color:#999;}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<h1>ELM327 C6</h1>\n"
"<small>SoftAP bridge - status, BLE, raw commands, profiles, telemetry</small>\n"
"\n"
"<div class=\"card\" id=\"statusCard\">\n"
"<h2>Status</h2>\n"
"<div id=\"statusOut\">loading...</div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>BLE</h2>\n"
"<button onclick=\"doScan()\">Scan</button>\n"
"<button onclick=\"refreshDevices()\">Refresh devices</button>\n"
"<div id=\"scanMsg\"></div>\n"
"<table id=\"devTable\"><thead><tr><th>#</th><th>Name</th><th>Addr</th><th>RSSI</th></tr></thead><tbody></tbody></table>\n"
"<div style=\"margin-top:8px;\">\n"
"<input id=\"selIndex\" type=\"number\" min=\"0\" placeholder=\"index\" style=\"width:70px;\">\n"
"<button onclick=\"doSelect()\">Select + Connect</button>\n"
"</div>\n"
"<div id=\"selectMsg\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Raw command</h2>\n"
"<input id=\"rawCmd\" type=\"text\" placeholder=\"e.g. 010C\" style=\"width:160px;\">\n"
"<button onclick=\"sendCmd()\">Send</button>\n"
"<pre id=\"cmdOut\">(no command sent yet)</pre>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Profiles</h2>\n"
"<select id=\"profileSel\"></select>\n"
"<button onclick=\"activateProfile()\">Activate</button>\n"
"<div id=\"profileMsg\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Live telemetry</h2>\n"
"<table id=\"teleTable\"><thead><tr><th>cmd</th><th>name</th><th>value</th><th>unit</th><th>age (s)</th></tr></thead><tbody></tbody></table>\n"
"<small id=\"teleEvent\"></small>\n"
"</div>\n"
"\n"
"<script>\n"
"async function getJSON(url, opts){\n"
"  const r = await fetch(url, opts);\n"
"  let body = null;\n"
"  try { body = await r.json(); } catch(e) {}\n"
"  return {ok: r.ok, status: r.status, body: body};\n"
"}\n"
"\n"
"function pill(ok, textTrue, textFalse){\n"
"  return '<span class=\"pill ' + (ok ? 'ok' : 'bad') + '\">' + (ok ? textTrue : textFalse) + '</span>';\n"
"}\n"
"\n"
"async function refreshStatus(){\n"
"  const res = await getJSON('/api/status');\n"
"  if (!res.body) { document.getElementById('statusOut').textContent = 'error loading status'; return; }\n"
"  const s = res.body;\n"
"  document.getElementById('statusOut').innerHTML =\n"
"    pill(s.ble_connected, 'BLE connected', 'BLE disconnected') +\n"
"    pill(s.elm_ready, 'ELM ready', 'ELM not ready') +\n"
"    '<span class=\"pill\">profile: ' + (s.active_profile || '-') + '</span>' +\n"
"    '<span class=\"pill\">uptime: ' + (s.uptime_s || 0) + 's</span>';\n"
"}\n"
"\n"
"async function doScan(){\n"
"  document.getElementById('scanMsg').textContent = 'scanning...';\n"
"  const res = await getJSON('/api/ble/scan', {method:'POST'});\n"
"  document.getElementById('scanMsg').textContent = res.ok ? 'scan started; click Refresh devices in a few seconds' : 'scan failed';\n"
"}\n"
"\n"
"async function refreshDevices(){\n"
"  const res = await getJSON('/api/ble/devices');\n"
"  const tbody = document.querySelector('#devTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  if (!res.body || !res.body.devices) return;\n"
"  res.body.devices.forEach(function(d){\n"
"    const tr = document.createElement('tr');\n"
"    tr.innerHTML = '<td>' + d.index + '</td><td>' + (d.name || '(unnamed)') + '</td><td>' + d.addr + '</td><td>' + d.rssi + '</td>';\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"}\n"
"\n"
"async function doSelect(){\n"
"  const idx = document.getElementById('selIndex').value;\n"
"  if (idx === '') { document.getElementById('selectMsg').textContent = 'enter an index'; return; }\n"
"  document.getElementById('selectMsg').textContent = 'connecting... (may take a few seconds)';\n"
"  const res = await getJSON('/api/ble/select', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({index: parseInt(idx, 10)})\n"
"  });\n"
"  document.getElementById('selectMsg').textContent = res.body ? JSON.stringify(res.body) : ('error ' + res.status);\n"
"  refreshStatus();\n"
"}\n"
"\n"
"async function sendCmd(){\n"
"  const cmd = document.getElementById('rawCmd').value.trim();\n"
"  if (!cmd) return;\n"
"  document.getElementById('cmdOut').textContent = 'sending...';\n"
"  const res = await getJSON('/api/elm/cmd', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({cmd: cmd})\n"
"  });\n"
"  document.getElementById('cmdOut').textContent = res.body ? JSON.stringify(res.body, null, 2) : ('HTTP ' + res.status);\n"
"}\n"
"\n"
"async function refreshProfiles(){\n"
"  const res = await getJSON('/api/profiles');\n"
"  const sel = document.getElementById('profileSel');\n"
"  if (!res.body || !res.body.profiles) return;\n"
"  const prev = sel.value;\n"
"  sel.innerHTML = '';\n"
"  res.body.profiles.forEach(function(name){\n"
"    const opt = document.createElement('option');\n"
"    opt.value = name; opt.textContent = name + (name === res.body.active ? ' (active)' : '');\n"
"    sel.appendChild(opt);\n"
"  });\n"
"  if (prev) sel.value = prev; else sel.value = res.body.active;\n"
"}\n"
"\n"
"async function activateProfile(){\n"
"  const name = document.getElementById('profileSel').value;\n"
"  if (!name) return;\n"
"  const res = await getJSON('/api/profiles/active', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({name: name})\n"
"  });\n"
"  document.getElementById('profileMsg').textContent = res.ok ? ('active profile: ' + name) : ('error ' + res.status);\n"
"  refreshProfiles();\n"
"}\n"
"\n"
"async function refreshTelemetry(){\n"
"  const res = await getJSON('/api/telemetry');\n"
"  if (!res.body) return;\n"
"  const tbody = document.querySelector('#teleTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  const nowMs = Date.now();\n"
"  (res.body.samples || []).slice().reverse().forEach(function(s){\n"
"    const tr = document.createElement('tr');\n"
"    const ageS = s.age_ms != null ? (s.age_ms/1000).toFixed(1) : '-';\n"
"    tr.innerHTML = '<td>' + s.cmd + '</td><td>' + s.name + '</td>' +\n"
"      '<td>' + (s.ok ? s.value.toFixed ? s.value.toFixed(2) : s.value : 'n/a') + '</td>' +\n"
"      '<td>' + (s.unit || '') + '</td><td>' + ageS + '</td>';\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"  const ev = res.body.last_event;\n"
"  document.getElementById('teleEvent').textContent = ev ? ('last event: ' + ev.kind) : '';\n"
"}\n"
"\n"
"function tick(){ refreshStatus(); refreshTelemetry(); }\n"
"refreshStatus(); refreshDevices(); refreshProfiles(); refreshTelemetry();\n"
"setInterval(tick, 2000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
