#pragma once

/* Minimal, framework-free HTML/JS control page served at GET /. Kept as a
 * plain C string (adjacent string-literal concatenation) so it can be baked
 * straight into the firmware image without a filesystem/SPIFFS partition. */
static const char TRANSPORT_HTTP_INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>ELM327 C6</title>\n"
"<style>\n"
"body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:16px;background:#111;color:#eee;}\n"
"h1{font-size:1.3em;margin:0 0 4px;} h2{font-size:1em;color:#8bd;margin:20px 0 8px;}\n"
".card{background:#1c1c1c;border:1px solid #333;border-radius:8px;padding:12px;margin-bottom:14px;}\n"
"button{background:#2b6cb0;color:#fff;border:none;border-radius:5px;padding:8px 12px;cursor:pointer;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"button:hover{background:#3182ce;} button.danger{background:#c53030;} button.danger:hover{background:#e53e3e;}\n"
"button.secondary{background:#2d3748;} button.secondary:hover{background:#4a5568;}\n"
"input,select{background:#000;color:#eee;border:1px solid #444;border-radius:5px;padding:8px;margin:2px 4px 2px 0;font-size:0.9em;}\n"
"table{width:100%;border-collapse:collapse;font-size:0.9em;}\n"
"td,th{border-bottom:1px solid #333;padding:6px;text-align:left;}\n"
"tr.devrow{cursor:pointer;} tr.devrow:hover{background:#222;}\n"
".pill{display:inline-block;padding:3px 8px;border-radius:10px;font-size:0.8em;margin:2px 6px 2px 0;}\n"
".ok{background:#22543d;color:#9ae6b4;} .bad{background:#742a2a;color:#feb2b2;}\n"
"pre{background:#000;border:1px solid #333;border-radius:5px;padding:8px;white-space:pre-wrap;word-break:break-all;max-height:180px;overflow:auto;}\n"
"small,.hint{color:#999;font-size:0.85em;}\n"
".grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;}\n"
".metric{background:#000;border:1px solid #333;border-radius:6px;padding:10px;}\n"
".metric .v{font-size:1.4em;font-weight:600;} .metric .k{color:#8bd;font-size:0.8em;}\n"
"@media (max-width:480px){.grid{grid-template-columns:1fr 1fr;}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<h1>ELM327 C6</h1>\n"
"<small>SoftAP bridge for phone control. Keep mobile data off while on ELM327-C6.</small>\n"
"\n"
"<div class=\"card\" id=\"statusCard\">\n"
"<h2>Status</h2>\n"
"<div id=\"statusOut\">loading...</div>\n"
"<div style=\"margin-top:8px;\">\n"
"<button onclick=\"refreshStatus()\">Refresh</button>\n"
"<button class=\"secondary\" onclick=\"doInit()\">Run init + 0100</button>\n"
"</div>\n"
"<div id=\"initMsg\" class=\"hint\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\" id=\"lteCard\">\n"
"<h2>LTE (EC200U)</h2>\n"
"<div id=\"lteOut\">loading...</div>\n"
"<div style=\"margin-top:8px;\">\n"
"<button onclick=\"refreshLte()\">Refresh</button>\n"
"<button class=\"secondary\" onclick=\"lteReconnect()\">Reconnect</button>\n"
"<button class=\"secondary\" onclick=\"lteTest()\">Test internet</button>\n"
"</div>\n"
"<div id=\"lteMsg\" class=\"hint\"></div>\n"
"<pre id=\"lteReport\" style=\"display:none;\"></pre>\n"
"</div>\n"
"\n"
"<div class=\"card\" id=\"uplinkCard\">\n"
"<h2>Cloud uplink</h2>\n"
"<div id=\"uplinkOut\">loading...</div>\n"
"<div style=\"margin-top:8px;\">\n"
"<label><input type=\"checkbox\" id=\"uplinkEn\"> Enable</label>\n"
"<input id=\"uplinkIv\" type=\"number\" min=\"1\" max=\"300\" style=\"width:70px;\" title=\"interval seconds\">\n"
"<span class=\"hint\">sec</span>\n"
"</div>\n"
"<div style=\"margin-top:6px;\">\n"
"<input id=\"uplinkDid\" type=\"text\" placeholder=\"device_id\" style=\"width:160px;\">\n"
"<input id=\"uplinkNid\" type=\"text\" placeholder=\"node_id\" style=\"width:140px;\">\n"
"</div>\n"
"<div style=\"margin-top:8px;\">\n"
"<button onclick=\"saveUplink()\">Save</button>\n"
"<button class=\"secondary\" onclick=\"sendUplinkNow()\">Send now</button>\n"
"<button class=\"secondary\" onclick=\"refreshUplink()\">Refresh</button>\n"
"</div>\n"
"<div id=\"uplinkMsg\" class=\"hint\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Live values</h2>\n"
"<div class=\"grid\" id=\"liveGrid\">\n"
"<div class=\"metric\"><div class=\"k\">RPM</div><div class=\"v\" id=\"vRpm\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Speed</div><div class=\"v\" id=\"vSpeed\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Coolant</div><div class=\"v\" id=\"vCool\">-</div></div>\n"
"<div class=\"metric\"><div class=\"k\">Voltage</div><div class=\"v\" id=\"vVolt\">-</div></div>\n"
"</div>\n"
"<table id=\"teleTable\" style=\"margin-top:10px;\"><thead><tr><th>cmd</th><th>name</th><th>value</th><th>unit</th><th>age</th></tr></thead><tbody></tbody></table>\n"
"<small id=\"teleEvent\"></small>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>BLE adapter</h2>\n"
"<button onclick=\"doScan()\">Scan</button>\n"
"<button onclick=\"refreshDevices()\">Refresh list</button>\n"
"<button class=\"danger\" onclick=\"doDisconnect()\">Disconnect</button>\n"
"<div id=\"scanMsg\" class=\"hint\"></div>\n"
"<table id=\"devTable\"><thead><tr><th>#</th><th>Name</th><th>Addr</th><th>RSSI</th></tr></thead><tbody></tbody></table>\n"
"<p class=\"hint\">Tap a row to connect. Your adapter may show as unnamed (MODAXE OBDII often has no BLE name). Prefer the strongest nearby device after phone Bluetooth is off. Connected adapters stop advertising — Disconnect to rescan.</p>\n"
"<div id=\"selectMsg\"></div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>OBD protocol</h2>\n"
"<p class=\"hint\">Ignition ON. Auto-detect uses ATSP0 + 0100 (can take 10–20s), then locks the found protocol.</p>\n"
"<button onclick=\"detectProtocol()\">Auto-detect protocol</button>\n"
"<div style=\"margin-top:8px;\">\n"
"<select id=\"protocolSel\"></select>\n"
"<button class=\"secondary\" onclick=\"applyProtocol()\">Apply manual</button>\n"
"</div>\n"
"<div id=\"protocolMsg\" class=\"hint\">Connect BLE adapter first, then detect or pick ATSP0–9.</div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>PID profile</h2>\n"
"<select id=\"profileSel\"></select>\n"
"<button onclick=\"activateProfile()\">Activate + init</button>\n"
"<div id=\"profileMsg\" class=\"hint\">Profiles set which PIDs to poll. Protocol (above) sets the bus (ATSPn).</div>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Diagnostics</h2>\n"
"<button onclick=\"readVin()\">Read VIN</button>\n"
"<button onclick=\"readDtc()\">Read DTCs</button>\n"
"<button class=\"danger\" onclick=\"clearDtc()\">Clear DTCs</button>\n"
"<div id=\"vinOut\" class=\"hint\">VIN: -</div>\n"
"<div id=\"dtcOut\" class=\"hint\">DTCs: -</div>\n"
"<p class=\"hint\">Clear DTCs needs Unsafe mode ON (below). MIL may relight after a drive cycle.</p>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Safety</h2>\n"
"<div id=\"safetyOut\">loading...</div>\n"
"<button class=\"secondary\" onclick=\"toggleUnsafe()\">Toggle Unsafe</button>\n"
"<p class=\"hint\">Unsafe ON allows Mode 04 (clear DTC). Mode 08 is never allowed.</p>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Device health</h2>\n"
"<div id=\"healthOut\">loading...</div>\n"
"<button onclick=\"refreshHealth()\">Refresh</button>\n"
"</div>\n"
"\n"
"<div class=\"card\">\n"
"<h2>Raw command</h2>\n"
"<input id=\"rawCmd\" type=\"text\" placeholder=\"e.g. 010C or ATRV\" style=\"width:180px;\">\n"
"<button onclick=\"sendCmd()\">Send</button>\n"
"<pre id=\"cmdOut\">(no command sent yet)</pre>\n"
"</div>\n"
"\n"
"<script>\n"
"async function getJSON(url, opts){\n"
"  try {\n"
"    const r = await fetch(url, Object.assign({cache:'no-store'}, opts||{}));\n"
"    let body = null;\n"
"    try { body = await r.json(); } catch(e) {}\n"
"    return {ok: r.ok, status: r.status, body: body};\n"
"  } catch(e) {\n"
"    return {ok: false, status: 0, body: null, error: String(e)};\n"
"  }\n"
"}\n"
"function pill(ok, t, f){ return '<span class=\"pill '+(ok?'ok':'bad')+'\">'+(ok?t:f)+'</span>'; }\n"
"\n"
"async function refreshStatus(){\n"
"  const res = await getJSON('/api/status');\n"
"  if (!res.body) {\n"
"    document.getElementById('statusOut').textContent =\n"
"      'Cannot reach ESP API. Join Wi-Fi ELM327-C6 / elm327c6, disable mobile data, open http://192.168.4.1/';\n"
"    return;\n"
"  }\n"
"  const s = res.body;\n"
"  document.getElementById('statusOut').innerHTML =\n"
"    pill(s.ble_connected, 'BLE connected', 'BLE disconnected') +\n"
"    pill(s.elm_ready, 'ELM ready', 'ELM not ready') +\n"
"    pill(s.poller_enabled, 'Polling on', 'Polling paused') +\n"
"    '<span class=\"pill\">peer: '+(s.peer_addr||'-')+'</span>' +\n"
"    '<span class=\"pill\">profile: '+(s.active_profile||'-')+'</span>' +\n"
"    '<span class=\"pill\">up: '+(s.uptime_s||0)+'s</span>';\n"
"  if (window._protoLabel) {\n"
"    document.getElementById('statusOut').innerHTML +=\n"
"      '<span class=\"pill\">proto: '+window._protoLabel+'</span>';\n"
"  }\n"
"}\n"
"\n"
"async function doInit(){\n"
"  document.getElementById('initMsg').textContent = 'Running AT init + 0100 (may take ~15s)...';\n"
"  const res = await getJSON('/api/elm/init', {method:'POST'});\n"
"  document.getElementById('initMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function doScan(){\n"
"  document.getElementById('scanMsg').textContent = 'scanning...';\n"
"  const res = await getJSON('/api/ble/scan', {method:'POST'});\n"
"  if (res.status === 409) {\n"
"    document.getElementById('scanMsg').textContent = (res.body && res.body.message) || 'already connected — disconnect first';\n"
"    return;\n"
"  }\n"
"  document.getElementById('scanMsg').textContent = res.ok ? 'scan started; refreshing in 6s...' : 'scan failed';\n"
"  if (res.ok) setTimeout(refreshDevices, 6500);\n"
"}\n"
"\n"
"async function refreshDevices(){\n"
"  const res = await getJSON('/api/ble/devices');\n"
"  const tbody = document.querySelector('#devTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  if (!res.body || !res.body.devices) return;\n"
"  document.getElementById('scanMsg').textContent = res.body.devices.length + ' device(s)';\n"
"  res.body.devices.forEach(function(d){\n"
"    const tr = document.createElement('tr');\n"
"    tr.className = 'devrow';\n"
"    tr.innerHTML = '<td>'+d.index+'</td><td>'+(d.name||'(unnamed)')+'</td><td>'+d.addr+'</td><td>'+d.rssi+'</td>';\n"
"    tr.onclick = function(){ connectIndex(d.index); };\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"}\n"
"\n"
"async function connectIndex(idx){\n"
"  document.getElementById('selectMsg').textContent = 'connecting index '+idx+'...';\n"
"  const res = await getJSON('/api/ble/select', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({index: idx})\n"
"  });\n"
"  document.getElementById('selectMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function doDisconnect(){\n"
"  const res = await getJSON('/api/ble/disconnect', {method:'POST'});\n"
"  document.getElementById('selectMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshStatus();\n"
"}\n"
"\n"
"async function sendCmd(){\n"
"  const cmd = document.getElementById('rawCmd').value.trim();\n"
"  if (!cmd) return;\n"
"  document.getElementById('cmdOut').textContent = 'sending...';\n"
"  const res = await getJSON('/api/elm/cmd', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({cmd: cmd})\n"
"  });\n"
"  document.getElementById('cmdOut').textContent = res.body ? JSON.stringify(res.body, null, 2) : ('HTTP '+res.status);\n"
"}\n"
"\n"
"async function refreshProtocols(){\n"
"  const res = await getJSON('/api/protocol');\n"
"  const sel = document.getElementById('protocolSel');\n"
"  if (!res.body || !res.body.protocols) return;\n"
"  const prev = sel.value;\n"
"  sel.innerHTML = '';\n"
"  res.body.protocols.forEach(function(p){\n"
"    const opt = document.createElement('option');\n"
"    opt.value = String(p.sp);\n"
"    opt.textContent = 'ATSP'+p.sp+' — '+p.label;\n"
"    sel.appendChild(opt);\n"
"  });\n"
"  if (res.body.configured_sp != null) {\n"
"    sel.value = String(res.body.configured_sp);\n"
"    window._protoLabel = res.body.configured_label || ('SP'+res.body.configured_sp);\n"
"  } else if (prev) {\n"
"    sel.value = prev;\n"
"  }\n"
"}\n"
"\n"
"function showProtocolResult(res, msgEl){\n"
"  if (!res.body) {\n"
"    msgEl.textContent = 'error '+res.status+(res.error?(' '+res.error):'');\n"
"    return;\n"
"  }\n"
"  const b = res.body;\n"
"  if (b.detected_sp != null) {\n"
"    window._protoLabel = b.detected_label || ('SP'+b.detected_sp);\n"
"    const sel = document.getElementById('protocolSel');\n"
"    if (sel) sel.value = String(b.detected_sp);\n"
"  } else if (b.sp != null) {\n"
"    window._protoLabel = b.label || ('SP'+b.sp);\n"
"  }\n"
"  msgEl.textContent = JSON.stringify(b);\n"
"}\n"
"\n"
"async function detectProtocol(){\n"
"  const el = document.getElementById('protocolMsg');\n"
"  el.textContent = 'Auto-detecting (ATSP0 + 0100)... keep ignition ON, wait up to ~20s';\n"
"  const res = await getJSON('/api/protocol/detect', {method:'POST'});\n"
"  showProtocolResult(res, el);\n"
"  refreshProtocols(); refreshProfiles(); refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function applyProtocol(){\n"
"  const sp = parseInt(document.getElementById('protocolSel').value, 10);\n"
"  if (isNaN(sp)) return;\n"
"  const el = document.getElementById('protocolMsg');\n"
"  el.textContent = 'Applying ATSP'+sp+' + init (may take ~15s)...';\n"
"  const res = await getJSON('/api/protocol', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({sp: sp})\n"
"  });\n"
"  showProtocolResult(res, el);\n"
"  refreshProtocols(); refreshProfiles(); refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"async function refreshProfiles(){\n"
"  const res = await getJSON('/api/profiles');\n"
"  const sel = document.getElementById('profileSel');\n"
"  if (!res.body || !res.body.profiles) return;\n"
"  const prev = sel.value;\n"
"  sel.innerHTML = '';\n"
"  res.body.profiles.forEach(function(name){\n"
"    const opt = document.createElement('option');\n"
"    opt.value = name; opt.textContent = name + (name === res.body.active ? ' (active)' : '');\n"
"    sel.appendChild(opt);\n"
"  });\n"
"  if (prev) sel.value = prev; else if (res.body.active) sel.value = res.body.active;\n"
"}\n"
"\n"
"async function activateProfile(){\n"
"  const name = document.getElementById('profileSel').value;\n"
"  if (!name) return;\n"
"  document.getElementById('profileMsg').textContent = 'activating '+name+' (init may take ~15s)...';\n"
"  const res = await getJSON('/api/profiles/active', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({name: name})\n"
"  });\n"
"  document.getElementById('profileMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshProfiles(); refreshProtocols(); refreshStatus(); refreshTelemetry();\n"
"}\n"
"\n"
"function setLive(id, sample){\n"
"  const el = document.getElementById(id);\n"
"  if (!sample || !sample.ok) { el.textContent = '-'; return; }\n"
"  if (sample.age_ms != null && sample.age_ms > 15000) { el.textContent = '-'; return; }\n"
"  const v = (typeof sample.value === 'number') ? sample.value.toFixed(1) : sample.value;\n"
"  el.textContent = v + (sample.unit ? (' '+sample.unit) : '');\n"
"}\n"
"\n"
"async function refreshTelemetry(){\n"
"  const res = await getJSON('/api/telemetry');\n"
"  if (!res.body) return;\n"
"  const samples = res.body.samples || [];\n"
"  const byName = {};\n"
"  samples.forEach(function(s){ byName[s.name] = s; byName[s.cmd] = s; });\n"
"  setLive('vRpm', byName.rpm || byName['010C']);\n"
"  setLive('vSpeed', byName.speed || byName['010D']);\n"
"  setLive('vCool', byName.coolant_c || byName['0105']);\n"
"  setLive('vVolt', byName.voltage || byName.ATRV);\n"
"  const tbody = document.querySelector('#teleTable tbody');\n"
"  tbody.innerHTML = '';\n"
"  samples.slice().reverse().forEach(function(s){\n"
"    const tr = document.createElement('tr');\n"
"    const ageS = s.age_ms != null ? (s.age_ms/1000).toFixed(1)+'s' : '-';\n"
"    tr.innerHTML = '<td>'+s.cmd+'</td><td>'+s.name+'</td>' +\n"
"      '<td>'+(s.ok ? (s.value.toFixed ? s.value.toFixed(2) : s.value) : 'n/a')+'</td>' +\n"
"      '<td>'+(s.unit||'')+'</td><td>'+ageS+'</td>';\n"
"    tbody.appendChild(tr);\n"
"  });\n"
"  const ev = res.body.last_event;\n"
"  document.getElementById('teleEvent').textContent = ev ? ('last event: '+ev.kind) : '';\n"
"}\n"
"\n"
"async function refreshLte(){\n"
"  const res = await getJSON('/api/lte');\n"
"  const el = document.getElementById('lteOut');\n"
"  if (!res.body){ el.textContent = 'LTE API error '+res.status; return; }\n"
"  const s = res.body;\n"
"  if (!s.enabled){ el.innerHTML = pill(false,'','LTE disabled'); return; }\n"
"  const rssi = s.rssi_dbm ? (s.rssi_dbm+' dBm') : (s.csq===99?'unknown':('csq '+s.csq));\n"
"  el.innerHTML =\n"
"    pill(s.uart_ok,'UART OK','UART fail') +\n"
"    pill(s.sim_ready,'SIM ready','SIM?') +\n"
"    pill(s.registered,'registered','not reg') +\n"
"    pill(s.attached,'data attached','not attached') +\n"
"    pill(s.ip_up,'IP up','no IP') +\n"
"    '<span class=\"pill\">signal: '+rssi+'</span>' +\n"
"    '<span class=\"pill\">op: '+(s.operator||'-')+'</span>' +\n"
"    '<span class=\"pill\">APN: '+(s.apn||'-')+'</span>' +\n"
"    (s.ip?('<span class=\"pill\">ip: '+s.ip+'</span>'):'') +\n"
"    (s.module?('<span class=\"pill\">'+s.module+'</span>'):'');\n"
"  if (s.last_error) document.getElementById('lteMsg').textContent = s.last_error;\n"
"}\n"
"\n"
"async function refreshUplink(){\n"
"  const res = await getJSON('/api/uplink');\n"
"  const el = document.getElementById('uplinkOut');\n"
"  if (!res.body){ el.textContent = 'uplink API error '+res.status; return; }\n"
"  const u = res.body;\n"
"  document.getElementById('uplinkEn').checked = !!u.enabled;\n"
"  document.getElementById('uplinkIv').value = u.interval_s || 5;\n"
"  document.getElementById('uplinkDid').value = u.device_id || '';\n"
"  document.getElementById('uplinkNid').value = u.node_id || '';\n"
"  const last = u.last || {};\n"
"  const age = last.age_ms != null ? (last.age_ms/1000).toFixed(1)+'s ago' : '-';\n"
"  el.innerHTML =\n"
"    pill(!!u.enabled,'uplink ON','uplink OFF') +\n"
"    pill(!!last.ok,'last OK','last fail/skip') +\n"
"    '<span class=\"pill\">HTTP '+(last.http_status||'-')+'</span>' +\n"
"    '<span class=\"pill\">'+(last.skipped?'skipped':'sent')+': '+(last.reason||'-')+'</span>' +\n"
"    '<span class=\"pill\">'+age+'</span>' +\n"
"    '<span class=\"pill\">schema '+(u.schema_id||'-')+'</span>';\n"
"  if (last.error) document.getElementById('uplinkMsg').textContent = last.error;\n"
"  else if (!last.ok && last.reason) document.getElementById('uplinkMsg').textContent = last.reason;\n"
"}\n"
"\n"
"async function saveUplink(){\n"
"  const body = {\n"
"    enabled: document.getElementById('uplinkEn').checked,\n"
"    interval_s: parseInt(document.getElementById('uplinkIv').value, 10) || 5,\n"
"    device_id: document.getElementById('uplinkDid').value.trim(),\n"
"    node_id: document.getElementById('uplinkNid').value.trim()\n"
"  };\n"
"  document.getElementById('uplinkMsg').textContent = 'saving...';\n"
"  const res = await getJSON('/api/uplink', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify(body)\n"
"  });\n"
"  document.getElementById('uplinkMsg').textContent = res.body && res.body.ok ? 'saved to NVS' : ('save failed '+res.status);\n"
"  refreshUplink();\n"
"}\n"
"\n"
"async function sendUplinkNow(){\n"
"  document.getElementById('uplinkMsg').textContent = 'sending (LTE HTTP may take ~30s)...';\n"
"  const res = await getJSON('/api/uplink/send', {method:'POST'});\n"
"  document.getElementById('uplinkMsg').textContent = res.body\n"
"    ? ((res.body.last&&res.body.last.ok)?'POST OK HTTP '+(res.body.last.http_status||'') : ('result: '+(res.body.last&&res.body.last.reason||res.body.error||res.status)))\n"
"    : ('error '+res.status);\n"
"  refreshUplink();\n"
"}\n"
"\n"
"async function lteReconnect(){\n"
"  document.getElementById('lteMsg').textContent = 'reconnecting modem...';\n"
"  const res = await getJSON('/api/lte/reconnect', {method:'POST'});\n"
"  document.getElementById('lteMsg').textContent = res.body ? JSON.stringify(res.body) : ('error '+res.status);\n"
"  refreshLte();\n"
"}\n"
"\n"
"async function lteTest(){\n"
"  document.getElementById('lteMsg').textContent = 'Testing LTE internet (register + PDP + ping, up to ~90s)...';\n"
"  const pre = document.getElementById('lteReport');\n"
"  pre.style.display = 'block';\n"
"  pre.textContent = 'running...';\n"
"  const res = await getJSON('/api/lte/test', {method:'POST'});\n"
"  if (res.body && res.body.report){\n"
"    pre.textContent = res.body.report;\n"
"    document.getElementById('lteMsg').textContent = res.body.internet ? 'INTERNET OK over LTE' : 'test done (see report)';\n"
"  } else {\n"
"    pre.textContent = 'error '+res.status+(res.error?(' '+res.error):'');\n"
"  }\n"
"  refreshLte();\n"
"}\n"
"\n"
"async function readVin(){\n"
"  const el = document.getElementById('vinOut');\n"
"  el.textContent = 'VIN: reading...';\n"
"  const res = await getJSON('/api/vin');\n"
"  if (res.body && res.body.vin) el.textContent = 'VIN: '+res.body.vin;\n"
"  else el.textContent = 'VIN: '+((res.body&&(res.body.note||res.body.error))||('error '+res.status));\n"
"}\n"
"\n"
"async function readDtc(){\n"
"  const el = document.getElementById('dtcOut');\n"
"  el.textContent = 'DTCs: reading...';\n"
"  const res = await getJSON('/api/dtc/read', {method:'POST'});\n"
"  if (!res.body){ el.textContent = 'DTCs: error '+res.status; return; }\n"
"  const st = (res.body.stored||[]);\n"
"  const pd = (res.body.pending||[]);\n"
"  el.textContent = 'Stored: '+(st.length?st.join(', '):'none')+' | Pending: '+(pd.length?pd.join(', '):'none');\n"
"}\n"
"\n"
"async function clearDtc(){\n"
"  if (!confirm('Clear stored DTCs? Requires Unsafe mode. This resets the MIL / readiness monitors.')) return;\n"
"  const el = document.getElementById('dtcOut');\n"
"  el.textContent = 'DTCs: clearing...';\n"
"  const res = await getJSON('/api/dtc/clear', {method:'POST'});\n"
"  if (res.status === 403){ el.textContent = 'Clear blocked: enable Unsafe mode first.'; return; }\n"
"  el.textContent = res.body ? ('Clear: '+JSON.stringify(res.body)) : ('error '+res.status);\n"
"  setTimeout(readDtc, 1500);\n"
"}\n"
"\n"
"async function refreshSafety(){\n"
"  const res = await getJSON('/api/safety');\n"
"  const el = document.getElementById('safetyOut');\n"
"  if (!res.body){ el.textContent = 'safety API error'; return; }\n"
"  window._unsafe = !!res.body.allow_unsafe;\n"
"  el.innerHTML = pill(res.body.allow_unsafe,'UNSAFE ON (Mode 04 allowed)','Safe mode (read-only)');\n"
"}\n"
"\n"
"async function toggleUnsafe(){\n"
"  const next = !window._unsafe;\n"
"  if (next && !confirm('Enable Unsafe mode? This allows clearing DTCs (Mode 04).')) return;\n"
"  const res = await getJSON('/api/safety', {\n"
"    method:'POST', headers:{'Content-Type':'application/json'},\n"
"    body: JSON.stringify({allow_unsafe: next})\n"
"  });\n"
"  if (res.body) window._unsafe = !!res.body.allow_unsafe;\n"
"  refreshSafety();\n"
"}\n"
"\n"
"async function refreshHealth(){\n"
"  const res = await getJSON('/api/health');\n"
"  const el = document.getElementById('healthOut');\n"
"  if (!res.body){ el.textContent = 'health API error'; return; }\n"
"  const h = res.body;\n"
"  const kb = function(b){ return Math.round((b||0)/1024)+' KB'; };\n"
"  el.innerHTML =\n"
"    '<span class=\"pill\">up: '+(h.uptime_s||0)+'s</span>' +\n"
"    '<span class=\"pill\">heap: '+kb(h.free_heap)+'</span>' +\n"
"    '<span class=\"pill\">min heap: '+kb(h.min_free_heap)+'</span>' +\n"
"    '<span class=\"pill\">reset: '+(h.reset_reason||'-')+'</span>' +\n"
"    '<span class=\"pill\">fw: '+(h.fw_version||'-')+'</span>' +\n"
"    '<span class=\"pill\">idf: '+(h.idf_version||'-')+'</span>';\n"
"}\n"
"\n"
"function tick(){ refreshStatus(); refreshTelemetry(); refreshUplink(); }\n"
"refreshStatus(); refreshDevices(); refreshProtocols(); refreshProfiles(); refreshTelemetry();\n"
"refreshLte(); refreshUplink(); refreshSafety(); refreshHealth();\n"
"setInterval(tick, 2000);\n"
"setInterval(function(){ refreshLte(); refreshHealth(); }, 10000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
