#pragma once
/* Auto-generated by scripts/gen_fleet_manifests.py — do not edit. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FLEET_MANIFEST_CATALOG_COUNT 2
#define FLEET_MANIFEST_MAX_READINGS 16
#define FLEET_MANIFEST_KEY_MAX 24
#define FLEET_MANIFEST_UNIT_MAX 8
#define FLEET_MANIFEST_TYPE_NAME_MAX 32

typedef enum {
    FLEET_MANIFEST_FLOAT = 1,
    FLEET_MANIFEST_UINT8 = 2,
    FLEET_MANIFEST_UINT16 = 3,
    FLEET_MANIFEST_INT32 = 4,
    FLEET_MANIFEST_STRING = 5,
} fleet_manifest_value_type_t;

typedef struct {
    char key[FLEET_MANIFEST_KEY_MAX];
    uint16_t tlv_id;
    fleet_manifest_value_type_t type;
    char unit[FLEET_MANIFEST_UNIT_MAX];
    bool required;
} fleet_manifest_reading_t;

typedef struct {
    uint16_t host_type_id;
    char host_type[FLEET_MANIFEST_TYPE_NAME_MAX];
    char description[64];
    uint8_t manifest_version;
    uint16_t report_interval_ms;
    uint8_t max_airtime_bytes;
    uint8_t reading_count;
    fleet_manifest_reading_t readings[FLEET_MANIFEST_MAX_READINGS];
} fleet_manifest_entry_t;

extern const fleet_manifest_entry_t fleet_manifest_catalog[FLEET_MANIFEST_CATALOG_COUNT];

const fleet_manifest_entry_t *fleet_manifest_find(uint16_t host_type_id);
const fleet_manifest_entry_t *fleet_manifest_find_by_name(const char *host_type);

#ifdef __cplusplus
}
#endif
