#!/usr/bin/env python3
"""Generate a draft Gerber/Excellon package for the fleet telematics carrier.

The board is intentionally a labeled module carrier, because the firmware repo
documents module-level wiring but not production footprints for every module.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile
import csv
import math
import shutil


BASE = Path(__file__).resolve().parent
OUT = BASE / "gerbers"
ZIP_PATH = BASE / "fleet_telematics_carrier_gerbers.zip"
BOARD_W = 122.0
BOARD_H = 82.0


@dataclass(frozen=True)
class Pad:
    ref: str
    pin: str
    name: str
    net: str
    x: float
    y: float
    drill: float
    pad: float
    shape: str = "circle"
    kind: str = "pth"


@dataclass(frozen=True)
class Route:
    layer: str
    net: str
    width: float
    points: tuple[tuple[float, float], ...]


@dataclass(frozen=True)
class Component:
    ref: str
    value: str
    notes: str


class Gerber:
    def __init__(self, name: str) -> None:
        self.name = name
        self.apertures: dict[str, int] = {}
        self.commands: list[str] = []

    def aperture(self, spec: str) -> int:
        if spec not in self.apertures:
            self.apertures[spec] = 10 + len(self.apertures)
        return self.apertures[spec]

    def select(self, code: int) -> None:
        self.commands.append(f"D{code}*")

    def flash_circle(self, x: float, y: float, diameter: float) -> None:
        code = self.aperture(f"C,{diameter:.3f}")
        self.select(code)
        self.commands.append(f"{xy(x, y)}D03*")

    def flash_rect(self, x: float, y: float, w: float, h: float) -> None:
        code = self.aperture(f"R,{w:.3f}X{h:.3f}")
        self.select(code)
        self.commands.append(f"{xy(x, y)}D03*")

    def line(self, points: list[tuple[float, float]], width: float) -> None:
        if len(points) < 2:
            return
        code = self.aperture(f"C,{width:.3f}")
        self.select(code)
        self.commands.append(f"{xy(*points[0])}D02*")
        for point in points[1:]:
            self.commands.append(f"{xy(*point)}D01*")

    def rect_outline(self, x0: float, y0: float, x1: float, y1: float, width: float) -> None:
        self.line([(x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)], width)

    def circle_outline(self, x: float, y: float, radius: float, width: float, segments: int = 48) -> None:
        pts = []
        for i in range(segments + 1):
            a = 2.0 * math.pi * i / segments
            pts.append((x + radius * math.cos(a), y + radius * math.sin(a)))
        self.line(pts, width)

    def render(self) -> str:
        lines = [
            f"G04 {self.name} generated by generate_gerbers.py*",
            "%FSLAX46Y46*%",
            "%MOMM*%",
            "%LPD*%",
            "G75*",
        ]
        for spec, code in sorted(self.apertures.items(), key=lambda item: item[1]):
            lines.append(f"%ADD{code}{spec}*%")
        lines.extend(self.commands)
        lines.append("M02*")
        return "\n".join(lines) + "\n"


def xy(x: float, y: float) -> str:
    return f"X{int(round(x * 1_000_000)):010d}Y{int(round(y * 1_000_000)):010d}"


FONT = {
    " ": ["00000", "00000", "00000", "00000", "00000", "00000", "00000"],
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "3": ["11110", "00001", "00001", "01110", "00001", "00001", "11110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    "5": ["11111", "10000", "10000", "11110", "00001", "00001", "11110"],
    "6": ["01110", "10000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00001", "01110"],
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "B": ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
    "C": ["01110", "10001", "10000", "10000", "10000", "10001", "01110"],
    "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
    "E": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "F": ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    "G": ["01110", "10001", "10000", "10111", "10001", "10001", "01110"],
    "H": ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    "I": ["01110", "00100", "00100", "00100", "00100", "00100", "01110"],
    "J": ["00111", "00010", "00010", "00010", "10010", "10010", "01100"],
    "K": ["10001", "10010", "10100", "11000", "10100", "10010", "10001"],
    "L": ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
    "M": ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    "N": ["10001", "11001", "10101", "10011", "10001", "10001", "10001"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "P": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "Q": ["01110", "10001", "10001", "10001", "10101", "10010", "01101"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "U": ["10001", "10001", "10001", "10001", "10001", "10001", "01110"],
    "V": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    "W": ["10001", "10001", "10001", "10101", "10101", "10101", "01010"],
    "X": ["10001", "10001", "01010", "00100", "01010", "10001", "10001"],
    "Y": ["10001", "10001", "01010", "00100", "00100", "00100", "00100"],
    "Z": ["11111", "00001", "00010", "00100", "01000", "10000", "11111"],
    "-": ["00000", "00000", "00000", "11111", "00000", "00000", "00000"],
    "+": ["00000", "00100", "00100", "11111", "00100", "00100", "00000"],
    "/": ["00001", "00001", "00010", "00100", "01000", "10000", "10000"],
    ".": ["00000", "00000", "00000", "00000", "00000", "01100", "01100"],
    ":": ["00000", "01100", "01100", "00000", "01100", "01100", "00000"],
    "_": ["00000", "00000", "00000", "00000", "00000", "00000", "11111"],
    "(": ["00010", "00100", "01000", "01000", "01000", "00100", "00010"],
    ")": ["01000", "00100", "00010", "00010", "00010", "00100", "01000"],
}


def draw_text(g: Gerber, text: str, x: float, y: float, scale: float = 0.32) -> None:
    cx = x
    cy = y
    dot = scale * 0.72
    for ch in text.upper():
        if ch == "\n":
            cy -= scale * 9
            cx = x
            continue
        pattern = FONT.get(ch, FONT[" "])
        for row, bits in enumerate(pattern):
            for col, bit in enumerate(bits):
                if bit == "1":
                    g.flash_rect(cx + col * scale, cy - row * scale, dot, dot)
        cx += scale * 6


components = [
    Component("J1", "1x12 2.54mm header", "ESP32-C6 Super Mini wiring header"),
    Component("U1", "TXS0108E level converter", "A side 3V3 to ESP32-C6, B side 5V to MCP2515"),
    Component("J2", "1x9 2.54mm header", "MCP2515 + TJA1050 module header"),
    Component("J3", "1x8 2.54mm header", "EC200U UART/control header"),
    Component("J4", "1x6 5.08mm terminal", "OBD/power/CAN cable terminal"),
    Component("J5", "1x4 5.08mm terminal", "XY-3606 buck module terminals"),
    Component("J6", "1x2 5.08mm terminal", "Separate EC200U VBAT input"),
    Component("SW1", "2-pin momentary switch", "EC200U PWRKEY to GND"),
    Component("MH1-MH4", "M3 NPTH mounting holes", "Aligns with 122 mm x 82 mm enclosure envelope"),
]


pads: list[Pad] = []
routes: list[Route] = []


def add_pad(ref: str, pin: str, name: str, net: str, x: float, y: float,
            drill: float = 0.90, pad: float = 1.80, shape: str = "circle",
            kind: str = "pth") -> None:
    pads.append(Pad(ref, pin, name, net, x, y, drill, pad, shape, kind))


def h_header(ref: str, x: float, y: float, pitch: float,
             pin_defs: list[tuple[str, str, str]], drill: float = 0.90,
             pad: float = 1.80) -> None:
    for i, (name, net, shape) in enumerate(pin_defs, start=1):
        add_pad(ref, str(i), name, net, x + (i - 1) * pitch, y, drill, pad, shape)


def v_header(ref: str, x: float, y: float, pitch: float,
             pin_defs: list[tuple[str, str, str]], drill: float = 0.90,
             pad: float = 1.80) -> None:
    for i, (name, net, shape) in enumerate(pin_defs, start=1):
        add_pad(ref, str(i), name, net, x, y - (i - 1) * pitch, drill, pad, shape)


def coord(ref: str, pin: str) -> tuple[float, float]:
    for pad in pads:
        if pad.ref == ref and pad.pin == pin:
            return pad.x, pad.y
    raise KeyError(f"{ref}.{pin}")


def route(layer: str, net: str, width: float, *pts: tuple[float, float]) -> None:
    routes.append(Route(layer, net, width, tuple(pts)))


# J1: labeled ESP32-C6 wiring header. Pin order is a carrier convention.
h_header(
    "J1", 16.0, 69.0, 2.54,
    [
        ("GND", "GND", "square"),
        ("3V3", "3V3", "circle"),
        ("GPIO14_INT", "ESP_INT_3V3", "circle"),
        ("GPIO16_LTE_RX", "LTE_TXD_TO_ESP", "circle"),
        ("GPIO17_LTE_TX", "ESP_TXD_TO_LTE", "circle"),
        ("GPIO20_CS", "ESP_CS_3V3", "circle"),
        ("GPIO21_SCK", "ESP_SCK_3V3", "circle"),
        ("GPIO22_MOSI", "ESP_MOSI_3V3", "circle"),
        ("GPIO23_MISO", "ESP_MISO_3V3", "circle"),
        ("5V_IN", "5V_SYS", "circle"),
        ("EN", "ESP_EN_SPARE", "circle"),
        ("GND", "GND", "circle"),
    ],
)

# U1: TXS0108E A/B header. Channel order matches the fanout to avoid crossings.
# OE is adjacent to VCCA so it can be tied high locally without weaving through
# the SPI/CAN fanout.
u1_y = 58.0
for idx, (pin, name, net) in enumerate(
    [
        ("A1", "VCCA", "3V3"),
        ("A2", "OE", "3V3"),
        ("A3", "GND", "GND"),
        ("A4", "A_MISO", "ESP_MISO_3V3"),
        ("A5", "A_MOSI", "ESP_MOSI_3V3"),
        ("A6", "A_SCK", "ESP_SCK_3V3"),
        ("A7", "A_CS", "ESP_CS_3V3"),
        ("A8", "A_INT", "ESP_INT_3V3"),
        ("A9", "NC", "NC"),
        ("A10", "NC", "NC"),
    ],
    start=1,
):
    add_pad("U1", pin, name, net, 58.0, u1_y - (idx - 1) * 2.54)

for idx, (pin, name, net) in enumerate(
    [
        ("B1", "VCCB", "5V_SYS"),
        ("B2", "GND", "GND"),
        ("B3", "B_MISO", "MCP_MISO_5V"),
        ("B4", "B_MOSI", "MCP_MOSI_5V"),
        ("B5", "B_SCK", "MCP_SCK_5V"),
        ("B6", "B_CS", "MCP_CS_5V"),
        ("B7", "B_INT", "MCP_INT_5V"),
        ("B8", "NC", "NC"),
        ("B9", "NC", "NC"),
        ("B10", "NC", "NC"),
    ],
    start=1,
):
    add_pad("U1", pin, name, net, 68.16, u1_y - (idx - 1) * 2.54)

# J2: MCP2515 module header.
v_header(
    "J2", 103.0, 62.0, 2.54,
    [
        ("VCC5", "5V_SYS", "square"),
        ("GND", "GND", "circle"),
        ("SO_MISO", "MCP_MISO_5V", "circle"),
        ("SI_MOSI", "MCP_MOSI_5V", "circle"),
        ("SCK", "MCP_SCK_5V", "circle"),
        ("CS", "MCP_CS_5V", "circle"),
        ("INT", "MCP_INT_5V", "circle"),
        ("CAN_H", "CAN_H", "circle"),
        ("CAN_L", "CAN_L", "circle"),
    ],
)

# J3: EC200U UART/control header.
h_header(
    "J3", 22.0, 20.0, 2.54,
    [
        ("VBAT", "LTE_VBAT", "square"),
        ("GND", "GND", "circle"),
        ("TXD", "LTE_TXD_TO_ESP", "circle"),
        ("RXD", "ESP_TXD_TO_LTE", "circle"),
        ("PWRKEY", "LTE_PWRKEY", "circle"),
        ("RESET_N", "LTE_RESET_N_SPARE", "circle"),
        ("NETLIGHT", "LTE_NETLIGHT_SPARE", "circle"),
        ("GND", "GND", "circle"),
    ],
)

# J4: OBD/power terminal. Pin names reference OBD-II DLC pins.
v_header(
    "J4", 7.0, 45.4, 5.08,
    [
        ("OBD16_12V", "OBD_12V", "square"),
        ("OBD4_GND", "GND", "circle"),
        ("OBD6_CANH", "CAN_H", "circle"),
        ("OBD14_CANL", "CAN_L", "circle"),
        ("OBD5_GND", "GND", "circle"),
        ("IGN_SPARE", "IGN_SPARE", "circle"),
    ],
    drill=1.30,
    pad=2.80,
)

# J5: XY-3606 buck terminals.
v_header(
    "J5", 112.0, 30.2, 5.08,
    [
        ("VIN+", "OBD_12V", "square"),
        ("VIN-", "GND", "circle"),
        ("OUT+", "5V_SYS", "circle"),
        ("OUT-", "GND", "circle"),
    ],
    drill=1.30,
    pad=2.80,
)

# J6: separate high-current LTE power input.
h_header(
    "J6", 22.0, 8.0, 5.08,
    [
        ("LTE_VBAT", "LTE_VBAT", "square"),
        ("GND", "GND", "circle"),
    ],
    drill=1.30,
    pad=2.80,
)

add_pad("SW1", "1", "PWRKEY", "LTE_PWRKEY", 48.0, 20.0, 0.90, 1.80)
add_pad("SW1", "2", "GND", "GND", 54.0, 20.0, 0.90, 1.80)

for ref, x, y in [("MH1", 8.0, 8.0), ("MH2", 114.0, 8.0), ("MH3", 8.0, 74.0), ("MH4", 114.0, 74.0)]:
    add_pad(ref, "1", "M3_NPTH", "NPTH", x, y, 3.20, 0.0, kind="npth")

# Signal routes: ESP -> TXS A side.
route("F_Cu", "ESP_INT_3V3", 0.28, coord("J1", "3"), coord("U1", "A8"))
route("F_Cu", "ESP_CS_3V3", 0.28, coord("J1", "6"), coord("U1", "A7"))
route("F_Cu", "ESP_SCK_3V3", 0.28, coord("J1", "7"), coord("U1", "A6"))
route("F_Cu", "ESP_MOSI_3V3", 0.28, coord("J1", "8"), coord("U1", "A5"))
route("F_Cu", "ESP_MISO_3V3", 0.28, coord("J1", "9"), coord("U1", "A4"))

# Signal routes: TXS B side -> MCP2515 module.
route("F_Cu", "MCP_MISO_5V", 0.28, coord("U1", "B3"), coord("J2", "3"))
route("F_Cu", "MCP_MOSI_5V", 0.28, coord("U1", "B4"), coord("J2", "4"))
route("F_Cu", "MCP_SCK_5V", 0.28, coord("U1", "B5"), coord("J2", "5"))
route("F_Cu", "MCP_CS_5V", 0.28, coord("U1", "B6"), coord("J2", "6"))
route("F_Cu", "MCP_INT_5V", 0.28, coord("U1", "B7"), coord("J2", "7"))

# LTE UART and PWRKEY.
route("F_Cu", "LTE_TXD_TO_ESP", 0.28, coord("J3", "3"), (27.08, 22.5), (14.0, 22.5), (14.0, 73.2), (23.62, 73.2), coord("J1", "4"))
route("F_Cu", "ESP_TXD_TO_LTE", 0.28, coord("J3", "4"), (29.62, 16.0), (12.0, 16.0), (12.0, 74.4), (26.16, 74.4), coord("J1", "5"))
route("F_Cu", "LTE_PWRKEY", 0.28, coord("J3", "5"), (32.16, 25.0), (48.0, 25.0), coord("SW1", "1"))

# CAN and power routes. Kept on bottom layer with wider traces.
route("B_Cu", "CAN_H", 0.40, coord("J4", "3"), (20.0, 35.24), (20.0, 28.0), (96.0, 28.0), (96.0, 44.22), coord("J2", "8"))
route("B_Cu", "CAN_L", 0.40, coord("J4", "4"), (17.0, 30.16), (17.0, 26.0), (98.0, 26.0), (98.0, 41.68), coord("J2", "9"))
route("B_Cu", "OBD_12V", 1.20, coord("J4", "1"), (17.0, 45.40), (17.0, 50.0), (108.0, 50.0), (108.0, 30.20), coord("J5", "1"))

# 5V and 3V3 run on the front upper corridor, away from the bottom CAN/OBD power.
route("F_Cu", "5V_SYS", 0.90, coord("J5", "3"), (118.0, 20.04), (118.0, 76.5), (38.86, 76.5), coord("J1", "10"))
route("F_Cu", "5V_SYS", 0.70, (103.0, 76.5), coord("J2", "1"))
route("F_Cu", "5V_SYS", 0.70, (68.16, 76.5), coord("U1", "B1"))
route("B_Cu", "3V3", 0.50, coord("J1", "2"), (18.54, 60.0), (58.0, 60.0), coord("U1", "A1"))
route("F_Cu", "3V3", 0.40, coord("U1", "A1"), coord("U1", "A2"))
route("B_Cu", "LTE_VBAT", 1.00, coord("J6", "1"), coord("J3", "1"))

# Common ground perimeter and short spurs. The perimeter keeps high/low grounds
# connected without vertical drops through unrelated connector pins.
route("B_Cu", "GND", 0.90, (2.0, 4.0), (120.0, 4.0), (120.0, 78.0), (2.0, 78.0), (2.0, 4.0))
for p in [coord("J4", "2"), coord("J4", "5")]:
    route("B_Cu", "GND", 0.50, p, (2.0, p[1]))
for p in [coord("J5", "2"), coord("J5", "4")]:
    route("B_Cu", "GND", 0.50, p, (120.0, p[1]))
for p in [coord("J6", "2"), coord("J3", "2"), coord("J3", "8"), coord("SW1", "2")]:
    route("B_Cu", "GND", 0.50, p, (p[0], 4.0))
for p in [coord("J1", "1"), coord("J1", "12")]:
    route("B_Cu", "GND", 0.50, p, (p[0], 78.0))
route("B_Cu", "GND", 0.50, coord("U1", "A3"), (2.0, coord("U1", "A3")[1]))
route("B_Cu", "GND", 0.50, coord("U1", "B2"), (120.0, coord("U1", "B2")[1]))
route("B_Cu", "GND", 0.50, coord("J2", "2"), (100.0, coord("J2", "2")[1]), (100.0, 78.0))


def build_layers() -> dict[str, Gerber]:
    layers = {
        "F_Cu": Gerber("front copper"),
        "B_Cu": Gerber("back copper"),
        "F_Mask": Gerber("front solder mask openings"),
        "B_Mask": Gerber("back solder mask openings"),
        "F_SilkS": Gerber("front silkscreen"),
        "Edge_Cuts": Gerber("board outline"),
    }

    layers["Edge_Cuts"].rect_outline(0.0, 0.0, BOARD_W, BOARD_H, 0.15)

    for pad in pads:
        if pad.kind == "npth":
            layers["F_SilkS"].circle_outline(pad.x, pad.y, 2.2, 0.12)
            continue

        for layer in (layers["F_Cu"], layers["B_Cu"]):
            if pad.shape == "square":
                layer.flash_rect(pad.x, pad.y, pad.pad, pad.pad)
            else:
                layer.flash_circle(pad.x, pad.y, pad.pad)
        for layer in (layers["F_Mask"], layers["B_Mask"]):
            if pad.shape == "square":
                layer.flash_rect(pad.x, pad.y, pad.pad + 0.20, pad.pad + 0.20)
            else:
                layer.flash_circle(pad.x, pad.y, pad.pad + 0.20)

    for r in routes:
        layers[r.layer].line(list(r.points), r.width)

    silk = layers["F_SilkS"]
    silk.rect_outline(14.0, 66.0, 46.0, 72.5, 0.12)
    draw_text(silk, "J1 ESP32-C6", 14.0, 76.8, 0.34)
    draw_text(silk, "VERIFY PIN ORDER", 50.0, 76.8, 0.30)

    silk.rect_outline(54.0, 33.0, 72.2, 61.5, 0.12)
    draw_text(silk, "U1 TXS0108E", 52.5, 64.8, 0.32)
    draw_text(silk, "A=3V3 B=5V", 52.5, 31.0, 0.28)

    silk.rect_outline(99.0, 39.0, 107.0, 64.5, 0.12)
    draw_text(silk, "J2 MCP2515", 86.5, 68.7, 0.32)
    draw_text(silk, "CAN MOD", 89.0, 36.8, 0.30)

    silk.rect_outline(19.5, 17.0, 42.2, 23.0, 0.12)
    draw_text(silk, "J3 EC200U", 20.0, 27.0, 0.32)

    silk.rect_outline(3.0, 17.0, 11.0, 48.2, 0.12)
    draw_text(silk, "J4 OBD", 2.5, 53.0, 0.32)
    draw_text(silk, "16 4 6 14 5", 13.0, 45.8, 0.25)

    silk.rect_outline(108.0, 11.5, 116.0, 33.2, 0.12)
    draw_text(silk, "J5 XY-3606", 90.0, 9.0, 0.32)

    silk.rect_outline(19.0, 5.0, 31.5, 11.0, 0.12)
    draw_text(silk, "J6 LTE PWR", 18.5, 3.5, 0.28)

    silk.rect_outline(46.0, 17.0, 56.0, 23.0, 0.12)
    draw_text(silk, "SW1 PWRKEY", 45.0, 27.0, 0.28)

    draw_text(silk, "FLEET C6 CARRIER REV A DRAFT", 34.0, 8.0, 0.30)
    draw_text(silk, "OBD 12V FUSE/TVS OFFBOARD", 34.0, 12.0, 0.25)

    for mh in [p for p in pads if p.kind == "npth"]:
        silk.circle_outline(mh.x, mh.y, 2.6, 0.12)
        draw_text(silk, mh.ref, mh.x - 2.5, mh.y + 5.0, 0.24)

    return layers


def write_drill(path: Path, npth: bool) -> None:
    selected = [p for p in pads if (p.kind == "npth") == npth]
    groups: dict[float, list[Pad]] = {}
    for pad in selected:
        groups.setdefault(pad.drill, []).append(pad)

    lines = [
        "M48",
        f"; {path.name}",
        "METRIC,LZ",
    ]
    for idx, drill in enumerate(sorted(groups), start=1):
        lines.append(f"T{idx:02d}C{drill:.3f}")
    lines.extend(["%", "G90", "M71"])
    for idx, drill in enumerate(sorted(groups), start=1):
        lines.append(f"T{idx:02d}")
        for pad in groups[drill]:
            lines.append(f"X{pad.x:.3f}Y{pad.y:.3f}")
    lines.append("M30")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_csvs() -> None:
    with (OUT / "bom.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["ref", "value", "notes"])
        for comp in components:
            writer.writerow([comp.ref, comp.value, comp.notes])

    with (OUT / "netlist.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["ref", "pin", "pin_name", "net", "x_mm", "y_mm"])
        for pad in sorted(pads, key=lambda p: (p.ref, p.pin)):
            writer.writerow([pad.ref, pad.pin, pad.name, pad.net, f"{pad.x:.2f}", f"{pad.y:.2f}"])


def route_segments(r: Route) -> list[tuple[tuple[float, float], tuple[float, float]]]:
    return list(zip(r.points, r.points[1:]))


def point_segment_distance(point: tuple[float, float], a: tuple[float, float],
                           b: tuple[float, float]) -> float:
    px, py = point
    ax, ay = a
    bx, by = b
    dx = bx - ax
    dy = by - ay
    if abs(dx) < 1e-9 and abs(dy) < 1e-9:
        return math.hypot(px - ax, py - ay)
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    x = ax + t * dx
    y = ay + t * dy
    return math.hypot(px - x, py - y)


def orientation(a: tuple[float, float], b: tuple[float, float],
                c: tuple[float, float]) -> float:
    return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])


def on_segment(a: tuple[float, float], b: tuple[float, float],
               c: tuple[float, float]) -> bool:
    return (
        min(a[0], c[0]) - 1e-7 <= b[0] <= max(a[0], c[0]) + 1e-7 and
        min(a[1], c[1]) - 1e-7 <= b[1] <= max(a[1], c[1]) + 1e-7
    )


def segments_intersect(a: tuple[float, float], b: tuple[float, float],
                       c: tuple[float, float], d: tuple[float, float]) -> bool:
    o1 = orientation(a, b, c)
    o2 = orientation(a, b, d)
    o3 = orientation(c, d, a)
    o4 = orientation(c, d, b)
    if o1 * o2 < -1e-7 and o3 * o4 < -1e-7:
        return True
    if abs(o1) <= 1e-7 and on_segment(a, c, b):
        return True
    if abs(o2) <= 1e-7 and on_segment(a, d, b):
        return True
    if abs(o3) <= 1e-7 and on_segment(c, a, d):
        return True
    if abs(o4) <= 1e-7 and on_segment(c, b, d):
        return True
    return False


def sanity_check() -> None:
    for pad in pads:
        if not (0.0 <= pad.x <= BOARD_W and 0.0 <= pad.y <= BOARD_H):
            raise ValueError(f"{pad.ref}.{pad.pin} outside board")
    for r in routes:
        for x, y in r.points:
            if not (0.0 <= x <= BOARD_W and 0.0 <= y <= BOARD_H):
                raise ValueError(f"route {r.net} outside board at {(x, y)}")

    routed_layers = {"F_Cu", "B_Cu"}
    for idx, a_route in enumerate(routes):
        if a_route.layer not in routed_layers:
            continue
        for b_route in routes[idx + 1:]:
            if b_route.layer != a_route.layer or b_route.net == a_route.net:
                continue
            for a0, a1 in route_segments(a_route):
                for b0, b1 in route_segments(b_route):
                    if segments_intersect(a0, a1, b0, b1):
                        raise ValueError(
                            f"{a_route.layer}: {a_route.net} crosses {b_route.net} "
                            f"between {a0}->{a1} and {b0}->{b1}"
                        )

    for r in routes:
        if r.layer not in routed_layers:
            continue
        for pad in pads:
            if pad.kind != "pth" or pad.net == r.net:
                continue
            keepout = pad.pad / 2.0 + r.width / 2.0 + 0.12
            for a, b in route_segments(r):
                if point_segment_distance((pad.x, pad.y), a, b) < keepout:
                    raise ValueError(
                        f"{r.layer}: route {r.net} too close to {pad.ref}.{pad.pin} "
                        f"({pad.net})"
                    )


def main() -> None:
    sanity_check()
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    layers = build_layers()
    for name, layer in layers.items():
        (OUT / f"fleet_telematics_carrier-{name}.gbr").write_text(layer.render(), encoding="utf-8")
    write_drill(OUT / "fleet_telematics_carrier-PTH.drl", npth=False)
    write_drill(OUT / "fleet_telematics_carrier-NPTH.drl", npth=True)
    write_csvs()

    if ZIP_PATH.exists():
        ZIP_PATH.unlink()
    with ZipFile(ZIP_PATH, "w", compression=ZIP_DEFLATED) as zf:
        for file in sorted(OUT.iterdir()):
            zf.write(file, arcname=file.name)

    print(f"Wrote {OUT}")
    print(f"Wrote {ZIP_PATH}")


if __name__ == "__main__":
    main()
