#!/usr/bin/env python3
"""Scan host/*/host.manifest.json and emit fleet_manifest_catalog.c."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
HOST_ROOT = REPO_ROOT / "hardware" / "fleet_telematics_carrier" / "host"
OUT_C = REPO_ROOT / "components" / "host_registry" / "fleet_manifest_catalog.c"
OUT_H = REPO_ROOT / "components" / "host_registry" / "include" / "fleet_manifest_catalog.h"

TYPE_MAP = {
    "float": "FLEET_MANIFEST_FLOAT",
    "uint8": "FLEET_MANIFEST_UINT8",
    "uint16": "FLEET_MANIFEST_UINT16",
    "int32": "FLEET_MANIFEST_INT32",
    "string": "FLEET_MANIFEST_STRING",
}


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load_manifests() -> list[tuple[str, dict]]:
    entries: list[tuple[str, dict]] = []
    for path in sorted(HOST_ROOT.glob("*/host.manifest.json")):
        if path.parent.name.startswith("."):
            continue
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        entries.append((path.parent.name, data))
    return entries


def emit_header(count: int) -> str:
    return f"""#pragma once
/* Auto-generated by scripts/gen_fleet_manifests.py — do not edit. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define FLEET_MANIFEST_CATALOG_COUNT {count}
#define FLEET_MANIFEST_MAX_READINGS 16
#define FLEET_MANIFEST_KEY_MAX 24
#define FLEET_MANIFEST_UNIT_MAX 8
#define FLEET_MANIFEST_TYPE_NAME_MAX 32

typedef enum {{
    FLEET_MANIFEST_FLOAT = 1,
    FLEET_MANIFEST_UINT8 = 2,
    FLEET_MANIFEST_UINT16 = 3,
    FLEET_MANIFEST_INT32 = 4,
    FLEET_MANIFEST_STRING = 5,
}} fleet_manifest_value_type_t;

typedef struct {{
    char key[FLEET_MANIFEST_KEY_MAX];
    uint16_t tlv_id;
    fleet_manifest_value_type_t type;
    char unit[FLEET_MANIFEST_UNIT_MAX];
    bool required;
}} fleet_manifest_reading_t;

typedef struct {{
    uint16_t host_type_id;
    char host_type[FLEET_MANIFEST_TYPE_NAME_MAX];
    char description[64];
    uint8_t manifest_version;
    uint16_t report_interval_ms;
    uint8_t max_airtime_bytes;
    uint8_t reading_count;
    fleet_manifest_reading_t readings[FLEET_MANIFEST_MAX_READINGS];
}} fleet_manifest_entry_t;

extern const fleet_manifest_entry_t fleet_manifest_catalog[FLEET_MANIFEST_CATALOG_COUNT];

const fleet_manifest_entry_t *fleet_manifest_find(uint16_t host_type_id);
const fleet_manifest_entry_t *fleet_manifest_find_by_name(const char *host_type);

#ifdef __cplusplus
}}
#endif
"""


def emit_source(entries: list[tuple[str, dict]]) -> str:
    lines = [
        "/* Auto-generated by scripts/gen_fleet_manifests.py — do not edit. */",
        '#include "fleet_manifest_catalog.h"',
        '#include "stdbool.h"',
        '#include <string.h>',
        "",
        "const fleet_manifest_entry_t fleet_manifest_catalog[FLEET_MANIFEST_CATALOG_COUNT] = {",
    ]

    for folder, m in entries:
        readings = m.get("readings", [])[:16]
        zigbee = m.get("zigbee", {})
        lines.append("  {")
        lines.append(f'    .host_type_id = {int(m["host_type_id"])},')
        lines.append(f'    .host_type = "{c_escape(m["host_type"])}",')
        lines.append(f'    .description = "{c_escape(m.get("description", folder))}",')
        lines.append(f'    .manifest_version = {int(m.get("manifest_version", 1))},')
        lines.append(
            f'    .report_interval_ms = {int(zigbee.get("report_interval_ms", 1000))},'
        )
        lines.append(
            f'    .max_airtime_bytes = {int(zigbee.get("max_airtime_bytes", 64))},'
        )
        lines.append(f"    .reading_count = {len(readings)},")
        lines.append("    .readings = {")
        for r in readings:
            t = TYPE_MAP.get(r.get("type", "float"), "FLEET_MANIFEST_FLOAT")
            req = "true" if r.get("required") else "false"
            unit = c_escape(r.get("unit", ""))
            lines.append("      {")
            lines.append(f'        .key = "{c_escape(r["key"])}",')
            lines.append(f'        .tlv_id = {int(r["tlv_id"])},')
            lines.append(f"        .type = {t},")
            lines.append(f'        .unit = "{unit}",')
            lines.append(f"        .required = {req},")
            lines.append("      },")
        lines.append("    },")
        lines.append("  },")

    lines.append("};")
    lines.append("")
    lines.append(
        "const fleet_manifest_entry_t *fleet_manifest_find(uint16_t host_type_id)"
    )
    lines.append("{")
    lines.append("  for (size_t i = 0; i < FLEET_MANIFEST_CATALOG_COUNT; i++) {")
    lines.append("    if (fleet_manifest_catalog[i].host_type_id == host_type_id) {")
    lines.append("      return &fleet_manifest_catalog[i];")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return NULL;")
    lines.append("}")
    lines.append("")
    lines.append(
        "const fleet_manifest_entry_t *fleet_manifest_find_by_name(const char *host_type)"
    )
    lines.append("{")
    lines.append("  if (!host_type) return NULL;")
    lines.append("  for (size_t i = 0; i < FLEET_MANIFEST_CATALOG_COUNT; i++) {")
    lines.append(
        "    if (strcmp(fleet_manifest_catalog[i].host_type, host_type) == 0) {"
    )
    lines.append("      return &fleet_manifest_catalog[i];")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return NULL;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    entries = load_manifests()
    if not entries:
        print("No host manifests found", file=sys.stderr)
        return 1

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(emit_header(len(entries)), encoding="utf-8")
    OUT_C.write_text(emit_source(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} manifests -> {OUT_C.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
